name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ci-cd-demo:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop and remove old container if exists
        run: |
          echo "Checking if old container exists..."
          if docker ps -a --filter "name=ci-cd-demo-container" -q | grep -q .; then
            echo "Old container found. Removing..."
            docker rm -f ci-cd-demo-container
          else
            echo "No existing container found."
          fi

      - name: Run new container
        run: |
          echo "Starting new container..."
          docker run -d -p 8080:80 --name ci-cd-demo-container ci-cd-demo:latest

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Wait for container to start
        run: sleep 5

      - name: Test container response
        run: |
          if curl -s http://localhost:8080 | grep -q "<html"; then
            echo "✅ Test passed: Container is serving content."
          else
            echo "❌ Test failed: Container did not respond correctly."
            echo "===== Container Logs ====="
            docker logs ci-cd-demo-container || true
            exit 1
          fi
